<?php 
/*
Plugin Name: PatientAccess Custom Plugin
Plugin URI: https://www.thomasiosprogrammer.com/
Description: PatientAccess Custom Plugin by Thomas
Version: 0.0.1
Author: Thomas Woodfin
Author URI: https://www.thomasiosprogrammer.com/
Text Domain: pcp
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
    require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}